### ISSUE TITLE
CCv0 | Update the CI for to work with the CCv0 requirements

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/tests#3887]
We now have separate branches and build/test jobs for CCv0 work, so we should start using that to make the CCv0 builds have awareness of this context and start adding customisations that we are using.

## Task list
- [x] Add an environment variable accessible by the different build jobs to reflect if we are running `CCv0` builds, or not
- [x] Add our build customisations into the scripts so we could potentially build a `CCv0` release from the branch, if the environment variable states we are running `CCv0`:
  - [x] Add skopeo, gnupg gpgme-devel as packages into the kata image. This might require changing the default image OS to fedora
  - [x] Add umoci into the rootfs before converting to an img as it is available as a package in the distro versions that Kata currently uses
  - [x] Updating the version of containerd that is pulled in to point to a containerd WIP PR as suggested by Mike Brown

**Comment by stevenhorsman** [comment]
The associate PR #3888 has merged, closing this item
