### ISSUE TITLE
tests | CCv0: Non-TEE, CC pod creation with Kubernetes from unencrypted image

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/tests#4557]
**As a** Kata CC contributor
**I want to** have automated testing of pod creation with Kubernetes on PRs
**so that** I can ensure that I haven't introduced any regressions

### Description

This is test case i2 from https://github.com/confidential-containers/community/issues/3: *Test we can use Kubernetes to create a Kata CC pod by pulling an unencrypted image inside the guest in a non-TEE environment*

Building on the work that Wainer did in https://github.com/kata-containers/tests/pull/4508 for a `crictl` environment and the ccv0 [script](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/ccv0.sh) and [doc](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md) we want to automate the test case 'Using Kubernetes for end-to-end provisioning of a Kata confidential containers pod with an unencrypted image' to do the same tests, but creating a Kubernetes pod rather than `crictl` one.

### Task list

- [x] Add a new CC Kubernetes job type
- [x] Add a job for the new CC Kubernetes job type: https://github.com/kata-containers/ci/issues/471
- [x] Add a new bats test of create a Kubernetes CC pod from an unsigned, unencrypted image
- [ ] ~Refactor `ccv0.sh` out into new integration test scripts to drive test~ Covered in https://github.com/kata-containers/kata-containers/issues/4132
- [x] Refactor common code in the `critctl` tests and Kubernetes into a shared library

**Comment by stevenhorsman** [comment]
@Megan-Wright and @GeorginaKin are actually working on this, but as they aren't currently project members I've assigned this to myself as a contact point

**Comment by stevenhorsman** [comment]
The tests and job changes have been completed in https://github.com/kata-containers/tests/pull/4729 and https://github.com/kata-containers/ci/pull/472. The remaining item to finish up `ccv0.sh` compatibility is covered under https://github.com/kata-containers/kata-containers/issues/4132
