### ISSUE TITLE
tests | CCv0: Non-TEE, CC pod creation with Kubernetes from the encrypted image

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/tests#4685]
**As a** Kata CC contributor
**I want to** have automated testing of pod creation from an encrypted image with Kubernetes on PRs
**so that** I can ensure that I haven't introduced any regressions

### Description

This is test case i3 from https://github.com/confidential-containers/community/issues/3: *Test we can use Kubernetes to create a Kata CC pod by pulling the encrypted ssh demo sample image inside the guest using an offline fs kbc*.

This is an automated test that builds on the work done in #4557 to get a Kata CC pod running on Kubernetes based on an unencrypted image. It can be based on the manual instructions in [Using Kubernetes to create a Kata confidential containers pod from the encrypted ssh demo sample image](https://github.com/kata-containers/kata-containers/blob/CCv0/docs/how-to/how-to-build-and-test-ccv0.md#using-kubernetes-to-create-a-kata-confidential-containers-pod-from-the-encrypted-ssh-demo-sample-image), which in turn was based on the [video demo](https://www.youtube.com/watch?v=1v1hxAWwHDo) and [doc](https://github.com/confidential-containers/documentation/tree/main/demos/ssh-demo)

There are a few extra compilations beyond the unencrypted version:
- The new job will need to set a parameter such as `AA_KBC="offline_fs_kbc"` and use this to ensure:
  - When building the rootfs ensure that the agent config file is added and `aa_kbc_params` is set in it similar to the existing code in https://github.com/kata-containers/kata-containers/blob/e4bae434dea76700a4adce144657fe060045b33b/docs/how-to/ccv0.sh#L285-L286
  - the kernel parameters are added during configuration similar to https://github.com/kata-containers/kata-containers/blob/e4bae434dea76700a4adce144657fe060045b33b/docs/how-to/ccv0.sh#L232-L235
  - These will possibly build on the work in https://github.com/kata-containers/tests/issues/4676 that should add the agent-config which might have mostly implemented them depend on the order of completion.
- For the ssh demo we also need to get the ssh-demo offline filesystem key file added to the rootfs similar https://github.com/kata-containers/kata-containers/blob/e4bae434dea76700a4adce144657fe060045b33b/docs/how-to/ccv0.sh#L283-L284. I'm not sure what parameter we should add to do this, as it is polluting the code a bit for a test case. @wainersm might have a good idea for this?
 - We need to get the demo kubernetes file from https://github.com/confidential-containers/documentation/blob/main/demos/ssh-demo/k8s-cc-ssh.yaml in order to create the ssh demo pod similar to https://github.com/kata-containers/kata-containers/blob/e4bae434dea76700a4adce144657fe060045b33b/docs/how-to/ccv0.sh#L405-L425
 - We want to connect to the pod to confirm that it is working like [on ](https://github.com/kata-containers/kata-containers/blob/e4bae434dea76700a4adce144657fe060045b33b/docs/how-to/ccv0.sh#L427-L433)
 - The pod will need deleting at the end of the test as usual

### Task list

- [ ] Add a new CC Kubernetes encrypted job type
- [ ] Add a job for the new CC Kubernetes encrypted job type
- [ ] Add a new bats test of create a Kubernetes CC pod from the encrypted ssh demo image encompassing the changes listed above
- [ ] Refactor `ccv0.sh` out into new integration test scripts to drive test

## Acceptance Criteria

**Given** a kata-containers PR is created against the `CCv0` branch
**When** the integration tests are triggered
**Then** a test job called something like `jenkins-ci-ubuntu-20.04-x86_64-cc_kubernetes-encrypted-ssh-demo` is run
  **And** from the job log you can see that a CC kubernetes pod has been created and connected to

**Comment by GeorginaKin** [comment]
Closing with the following PRs being merged:
https://github.com/kata-containers/kata-containers/pull/4529
https://github.com/kata-containers/kata-containers/pull/4537
https://github.com/kata-containers/tests/pull/4866
